

export const GET_ADMINS_BEGIN = 'GET_ADMINS_BEGIN';
export const GET_ADMINS_ERROR = 'GET_ADMINS_ERROR';
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS';

export const CREATE_NEW_ADMIN = 'CREATE_NEW_ADMIN';



// staff
export const GET_STAFFS_BEGIN = 'GET_STAFFS_BEGIN';
export const GET_STAFFS_ERROR = 'GET_STAFFS_ERROR';
export const GET_STAFFS_SUCCESS = 'GET_STAFFS_SUCCESS';

export const CREATE_NEW_STAFF = 'CREATE_NEW_STAFF';

export const UPDATE_EXISTING_STAFF = 'UPDATE_EXISTING_STAFF';
export const GET_SINGLE_STAFF_BEGIN = 'GET_SINGLE_STAFF_BEGIN';
export const GET_SINGLE_STAFF_ERROR = 'GET_SINGLE_STAFF_ERROR';
export const GET_SINGLE_STAFF_SUCCESS = 'GET_SINGLE_STAFF_SUCCESS';

// cashFlow
export const GET_CASHFLOWS_BEGIN = 'GET_CASHFLOWS_BEGIN';
export const GET_CASHFLOWS_ERROR = 'GET_CASHFLOWS_ERROR';
export const GET_CASHFLOWS_SUCCESS = 'GET_CASHFLOWS_SUCCESS';

export const CREATE_NEW_CASHFLOW = 'CREATE_NEW_CASHFLOW';

export const UPDATE_EXISTING_CASHFLOW = 'UPDATE_EXISTING_CASHFLOW';
export const GET_SINGLE_CASHFLOW_BEGIN = 'GET_SINGLE_CASHFLOW_BEGIN';
export const GET_SINGLE_CASHFLOW_ERROR = 'GET_SINGLE_CASHFLOW_ERROR';
export const GET_SINGLE_CASHFLOW_SUCCESS = 'GET_SINGLE_CASHFLOW_SUCCESS';

// BLOODDONATE
export const GET_BLOODDONATES_BEGIN = 'GET_BLOODDONATES_BEGIN';
export const GET_BLOODDONATES_ERROR = 'GET_BLOODDONATES_ERROR';
export const GET_BLOODDONATES_SUCCESS = 'GET_BLOODDONATES_SUCCESS';

export const CREATE_NEW_BLOODDONATE = 'CREATE_NEW_BLOODDONATE';

export const UPDATE_EXISTING_BLOODDONATE = 'UPDATE_EXISTING_BLOODDONATE';
export const GET_SINGLE_BLOODDONATE_BEGIN = 'GET_SINGLE_BLOODDONATE_BEGIN';
export const GET_SINGLE_BLOODDONATE_ERROR = 'GET_SINGLE_BLOODDONATE_ERROR';
export const GET_SINGLE_BLOODDONATE_SUCCESS = 'GET_SINGLE_BLOODDONATE_SUCCESS';

// bloodStorage
export const GET_BLOODSTORAGES_BEGIN = 'GET_BLOODSTORAGES_BEGIN';
export const GET_BLOODSTORAGES_ERROR = 'GET_BLOODSTORAGES_ERROR';
export const GET_BLOODSTORAGES_SUCCESS = 'GET_BLOODSTORAGES_SUCCESS';

export const CREATE_NEW_BLOODSTORAGE = 'CREATE_NEW_BLOODSTORAGE';

export const UPDATE_EXISTING_BLOODSTORAGE = 'UPDATE_EXISTING_BLOODSTORAGE';
export const GET_SINGLE_BLOODSTORAGE_BEGIN = 'GET_SINGLE_BLOODSTORAGE_BEGIN';
export const GET_SINGLE_BLOODSTORAGE_ERROR = 'GET_SINGLE_BLOODSTORAGE_ERROR';
export const GET_SINGLE_BLOODSTORAGE_SUCCESS = 'GET_SINGLE_BLOODSTORAGE_SUCCESS';


// infor
export const GET_INFORS_BEGIN = 'GET_INFORS_BEGIN';
export const GET_INFORS_ERROR = 'GET_INFORS_ERROR';
export const GET_INFORS_SUCCESS = 'GET_INFORS_SUCCESS';

export const CREATE_NEW_INFOR = 'CREATE_NEW_INFOR';

export const UPDATE_EXISTING_INFOR = 'UPDATE_EXISTING_INFOR';
export const GET_SINGLE_INFOR_BEGIN = 'GET_SINGLE_INFOR_BEGIN';
export const GET_SINGLE_INFOR_ERROR = 'GET_SINGLE_INFOR_ERROR';
export const GET_SINGLE_INFOR_SUCCESS = 'GET_SINGLE_INFOR_SUCCESS';